{% set version = "1.0.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggmulti
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggmulti_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggmulti/ggmulti_{{ version }}.tar.gz
  sha256: 23961f51599a115fb540eed4d4b8b2e19b36b2d26ede446bbaa66a57a339301c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-tidyr

test:
  commands:
    - $R -e "library('ggmulti')"           # [not win]
    - "\"%R%\" -e \"library('ggmulti')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggmulti
  license: GPL-2.0-only
  summary: It provides materials (i.e. 'serial axes' objects, Andrew's plot, various glyphs for scatter plot) to visualize high dimensional data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
